class SaleItem(Base):
    id = Column(Integer, primary_key=True)
    sale_id = Column(Integer, ForeignKey("sale.id"))
    product_id = Column(Integer, ForeignKey("product.id"))
    # variant_id = Column(Integer, ForeignKey("productvariant.id"), nullable=True)
    quantity = Column(Integer)
    unit_price = Column(Float)
    discount = Column(Float, default=0.0)
    tax = Column(Float)
    subtotal = Column(Float)
